os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "10.13.0"
sudo: false
cache:
  directories:
    - node
    - node_modules
env:
  global:
    - NODE_VERSION=10.13.0
before_install:
  - sudo apt-get install libpng-dev
  - npm i -g npm
  - npm install -g typescript
install:
  - npm install
  - cd backend
  - npm install
script:
  - npm run-script build:prod
  - npm run-script pack
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
